### ISSUE TITLE
Restablecer por Telefono

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#101]
Acomodar el recuadro del teléfono en restablecer por medio de teléfono, así como los botones de cancelar y continuar, ya que no están centrados y están pegados al borde inferior.

![image](https://github.com/createchsoftware/armony/assets/159207460/15adaec4-3a46-4fa3-986b-6f285b436730)

**Comment by yahirsaavedra** [comment]
Puede resolverse con un salto de linea, pero queda pendiente probar funcionalidad de la API debido a limitaciones tecnicas

**Comment by yahirsaavedra** [comment]
Funcional
