### ISSUE TITLE
No cargan servicios de spa

### ISSUE THREAD

**Issue by yahirsaavedra** [createchsoftware/armony#114]
Solicitar al usuario que elija una categoria, mientras no carguen los servicios porque no hay categoria seleccionada

![image](https://github.com/createchsoftware/armony/assets/51274659/526806b6-27f9-448b-900b-0719b598d4e7)

**Comment by ItsJorgeRdz03** [comment]
Por defecto va a cargar los tratamientos faciales y ahora mientras carga sale el mensaje de "Cargando..."
