### ISSUE TITLE
Remover datos estaticos de Servicios similares

### ISSUE THREAD

**Issue by yahirsaavedra** [createchsoftware/armony#117]
Sustituir por la leyenda "Cargando..."

![image](https://github.com/createchsoftware/armony/assets/51274659/bbf2621a-aa80-44aa-9856-ac14de5e0357)

**Comment by ItsJorgeRdz03** [comment]
Se modificaron los datos para que ahora diga "Cargando" en cada uno de los servicios por mostrar.
![image](https://github.com/createchsoftware/armony/assets/82615294/5d1911a0-114e-42fe-9186-427ec5458039)
