### ISSUE TITLE
GENERAL - ERROR CON LA CONEXIÓN A BASE DE DATOS

### ISSUE THREAD

**Issue by yahirsaavedra** [createchsoftware/armony#16]
Desde el Departamento de Testing, se detectó un fallo con la base de datos cuando se intentan realizar consultas por un tiempo prolongado.

MySQL tiene por defecto un tiempo aproximado de 8 horas entre cada sesión que se abre (solicitud de conexión desde el backend) para realizar consultas que se quedarán registradas en la base de datos.

Cuando este tiempo transcurre, la sesión expira y no es posible realizar más consultas hasta que se reinicie la página desde el servidor.

En otras palabras, la conexión se "ahoga" y el backend piensa que todavía sigue abierta, cuando ya no lo está, dando como resultado que la página deje de funcionar pasada una cierta cantidad de horas por fallos a la conexión del servidor de la base de datos.

**Posible solución**: En lugar de realizar una conexión por cada vez que se inicia la página, realizarla por cada vez que se haga una consulta. La desventaja es que el sistema se hará ligeramente más lento, pero permitirá realizar consultas por tiempos prolongados.

**Comment by Julian-Sandoval-x** [comment]
Modifique la conexión de la base de datos cambiando  _"createConnection()"_ por _"poolConnection()"_. con el método _poolConnection()_ tendremos una "piscina" de conexiones en la que cada vez que alguien necesite acceder a la base de datos entra a esta "piscina" y una vez terminado la conexión sale dejando ese espacio disponible para otra persona o proceso.

**Soluciones obtenidas al realizar el cambio**

- Se puede realizar más de una petición a la base de datos sin tener que reiniciar el servidor.
- Conexión más estable.
- Evitamos sobrecargar la página con diversas conexión a la vez provenientes de una sola persona.
**Código de nueva conexión a la base de datos**
![imagen_2024-05-01_234936139](https://github.com/createchsoftware/armony/assets/76192811/986df689-70d1-4f08-9517-81d9d7abfa78)

**Comment by yahirsaavedra** [comment]
Solución efectiva por el momento, cerrando issue

**Comment by yahirsaavedra** [comment]
![image](https://github.com/createchsoftware/armony/assets/51274659/95684531-335e-4be2-a183-aa8c6f1c54cd)

Nuevamente está ocurriendo el mismo error, pero con la solución ya planteada. Este error ocurre aproximadamente 5 minutos después de iniciar el servidor.

**Comment by Julian-Sandoval-x** [comment]
![image](https://github.com/createchsoftware/armony/assets/76192811/42032fe5-9ec7-4346-9d4e-1e9437f8f908)
Se agrego la función setTimeout con la cual en caso que no se conecte correctamente a la base de datos intente una reconexión pasado un segundo

**Comment by yahirsaavedra** [comment]
Desafortunadamente, la solución no está funcionando. Hay que probar con otro método.

**Comment by Julian-Sandoval-x** [comment]
Se realizaron modificaciones dentro dentro de la función y configuración de la conexión con la base de datos.
Dentro de la configuración se redujo el limite de conexiones a 30 para fines prácticos.
En la función de conexión 

- Se elimino el _setTimeout_.
- Se elimino el _await_ para crear la conexión debido a que resultaba innecesario
- Se creo la variable pool la cual almacenara la conexión.
- Se realiza la conexión y se capturan todos los errores para posteriormente mostrarlos por consola.
- En la función _endConnection_ ahora se verifica que exista una conexión.
![image](https://github.com/createchsoftware/armony/assets/76192811/6ae8de3d-fc4c-4b4e-8602-2813980da294)

**Comment by yahirsaavedra** [comment]
PROYECTO CERRADO
