### ISSUE TITLE
Adaptar Pantallas

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#18]
Adaptar las pantallas, ya que se desfasa en ciertas resoluciones de pantalla y se desacomoda algunos diseños como botones, texto entre otros. Por ejemplo la pantalla de productos, la mayoría del apartado de Inicia sesión, como el propio inicio de sesión, restablecer contraseña, crear cuenta.

![Productos](https://github.com/createchsoftware/armony/assets/159207460/4dc6db1d-3df1-43e5-9118-84797b9da327)
Como por ejemplo en productos los botones de ver mas se desacomoda.

![Crear Cuenta](https://github.com/createchsoftware/armony/assets/159207460/f2a60d41-ec41-4749-b83c-ea8f82e7c16f)
Como por ejemplo en crear cuenta el pie de pagina de armony se sobrepone con la creación de cuenta y a su vez creación de cuenta no se ve completada.

**Comment by ItsJorgeRdz03** [comment]
Ya se adaptaron las pantallas de productos y de los procesos de login, en el caso de los procesos de login ya se hicieron responsive
