### ISSUE TITLE
Boton Finalizar

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#19]
Centrar el botón finalizar en el paso 4 de restablecer tu contraseña.
![BotonFinalizar](https://github.com/createchsoftware/armony/assets/159207460/a73dd8c1-88af-471e-9819-bc7db3dabc27)
Ya que esta muy pegado a la izquierda.

**Comment by ItsJorgeRdz03** [comment]
El botón ya está centrado
