### ISSUE TITLE
Encabezado

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#21]
En Spa, Estetica, Restablecer contraseña, Crear Cuenta, el encabezado no es estático, se transparenta con lo que hay detrás.
![Encabezado](https://github.com/createchsoftware/armony/assets/159207460/ffe151d7-16b1-445a-aa62-01a674bfa6ab)

**Comment by adriandrs** [comment]
Resuelto

**Comment by antonioEsB** [comment]
Solamente se corrigió en estética
![image](https://github.com/createchsoftware/armony/assets/159207460/04960e95-228d-4601-8fe3-6ee0f06856d8)
![image](https://github.com/createchsoftware/armony/assets/159207460/813d6f58-3151-45d8-8384-df8ab4254902)
![image](https://github.com/createchsoftware/armony/assets/159207460/aa5eec98-0e9e-427f-8df8-306b6d6edbb2)

**Comment by ItsJorgeRdz03** [comment]
Ya se corrigío el encabezado transparente.
![image](https://github.com/createchsoftware/armony/assets/82615294/5df5676e-ba35-498f-b25c-0aaabb7613a7)
![image](https://github.com/createchsoftware/armony/assets/82615294/9c89a2c0-6e6f-4e8d-9960-0f2b44fc77f0)
![image](https://github.com/createchsoftware/armony/assets/82615294/3c649ba8-ea93-4f16-8560-3f2ca8fcbca7)
