### ISSUE TITLE
El que es perico ¿donde quiera es verde?

### ISSUE THREAD

**Issue by yahirsaavedra** [createchsoftware/armony#31]
El verde no se distingue muy bien en el banner, buscar una forma de hacer el texto mas claro o cambiar de color. De aplicarse lo anterior, que sea consistente con la pagina de Servicios de spa
![image](https://github.com/createchsoftware/armony/assets/51274659/80b25bc1-358c-463f-8fd3-5cfb78ac4962)

**Comment by ItsJorgeRdz03** [comment]
Aumenté la opacidad en los cuadros para que no se pierdan las letras, en cuanto al navbar, no me ocurre el error asi que imagino que ya está solucionado, en caso de que no sea así vuelvan a abrir el issue para que lo cheque
