### ISSUE TITLE
Carrusel de pilares-Pagina Principal Armony

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#38]
Poner etiquetas en los ver más del carrusel de los pilares y modificar los botones de las flechas ya que están mal centradas, seguir el diseño proporcionado.
![armony1](https://github.com/createchsoftware/armony/assets/159207460/2df90501-8337-4135-b4c2-9c1541ee0e90)
![armony2](https://github.com/createchsoftware/armony/assets/159207460/bf4fd1a4-5091-4b7a-8566-d6a08f6e701b)

**Comment by adriandrs** [comment]
Resuelto
