### ISSUE TITLE
Conoce el potencial... -Pagina Principal Armony

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#39]
Falta el icono en conoce el potencial... y esta mal escrito ya que dice suscripción y debe de decir rango.
![armony3](https://github.com/createchsoftware/armony/assets/159207460/a7e08e97-a515-4d90-b984-c66c76aec7fa)
![armony4](https://github.com/createchsoftware/armony/assets/159207460/0e7aa0a0-c2cf-4d19-a84a-9dfe796e188e)

**Comment by adriandrs** [comment]
Resuelto
