### ISSUE TITLE
Boton regresar 

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#49]
No funciona el botón regresar tanto en restablecer contraseña, como crear cuenta.
![armony12](https://github.com/createchsoftware/armony/assets/159207460/282816d7-467e-40cd-b0ab-f07d0d009893)

**Comment by yahirsaavedra** [comment]
#52

**Comment by yahirsaavedra** [comment]
Boton regresar funciona, pendiente boton cancelar
