### ISSUE TITLE
Agregar foto

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#54]
Cambiar la imagen a un botón y al darle clic aparezca una etiqueta, ya que no funciona.
![image](https://github.com/createchsoftware/armony/assets/159207460/3a7371fb-9a5c-4181-bfbd-050b9f57c0ab)

**Comment by yahirsaavedra** [comment]
Se está trabajando en la conexión de una API para subir imagenes, a cargo de @Julian-Sandoval-x.

**Comment by yahirsaavedra** [comment]
Ya se pueden subir avatares, parcialmente funcional
