### ISSUE TITLE
Agregar y botones - Carrusel Productos

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#59]
Poner una etiqueta en agregar y los botones no están centrados, seguir el diseño proporcionado.
![armony17](https://github.com/createchsoftware/armony/assets/159207460/87359db4-1fd8-4244-9d90-fb827b46840d)
![image](https://github.com/createchsoftware/armony/assets/159207460/bcaeac9a-7d5a-475a-a44d-4a609136e477)

**Comment by yahirsaavedra** [comment]
Se da prioridad a que ya sea funcional. **NO MARCAR como resuelto hasta que ya sea funcional.**
