### ISSUE TITLE
Ver tratamientos

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#60]
Mal direccionamiento en el botón de ver tratamientos, tanto en spa como estética, ya que te debe de redirigir a los tratamientos que se ofrecen.
![armony18](https://github.com/createchsoftware/armony/assets/159207460/a3da9851-936b-472f-9f07-739654436371)

**Comment by ItsJorgeRdz03** [comment]
Corregido el redireccionamiento.
