### ISSUE TITLE
Tratamientos - Mejor acomodo

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#61]
En servicios spa y estética mejor acomodo del carrito y el corazón de favorito ya que se pierde con el fondo,, siguiendo el diseño proporcionado, o aumentar la opacidad de las imágenes para que se distingan mejor los iconos.
![armony19](https://github.com/createchsoftware/armony/assets/159207460/406c9386-61b5-440c-92f6-eaf517451a7a)
![armony20](https://github.com/createchsoftware/armony/assets/159207460/682621a6-80f3-48a4-8b7f-e9979126c9bb)

**Comment by ItsJorgeRdz03** [comment]
Se ajustó el acomodo de los botones en base al diseño, se cambió el color por un gris más oscuro y se disminyó un poco la opacidad.
