### ISSUE TITLE
Descripción del tratamiento

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#62]
Acomodar las imágenes en el la descripción del servicio, tanto como en spa y estética.
![image](https://github.com/createchsoftware/armony/assets/159207460/16a96b31-7829-448c-97fa-83d68f3c6a9a)

**Comment by ItsJorgeRdz03** [comment]
Se acomodaron las imágenes para quedar más centradas, si sigue habiendo problemas, vuelvan a abrir el issue.
