### ISSUE TITLE
Registrar cita

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#63]
En registrar cita que te mande a iniciar sesión y te redireccione a la agenda o poner una etiqueta, tanto como en spa y estética.
![armony21](https://github.com/createchsoftware/armony/assets/159207460/e17cffb3-f786-49e3-88c7-6475b079f97a)

**Comment by ItsJorgeRdz03** [comment]
Añadida validación de login para el redireccionamiento de agendar cita.
