### ISSUE TITLE
Redes Sociales

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#76]
Redirigir a las redes sociales, ya que no funcionan.
![armony28](https://github.com/createchsoftware/armony/assets/159207460/020ddf04-ae24-43a3-918d-125b179f04db)

**Comment by yahirsaavedra** [comment]
Etiquetando como duda, debido a que solamente se tienen las redes sociales de la empresa desarrolladora, que es Createch. Un negocio deberia tener redes sociales separadas (o al menos es lo ideal).

En caso de que se usen las redes sociales de Createch, se van a utilizar. Por mientras, dejaré este issue abierto.

**Comment by yahirsaavedra** [comment]
Se agregaron por el momento las redes sociales de Createch.
