### ISSUE TITLE
Icono Carrito

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#77]
En donde este un icono de carrito, poner una etiqueta, ya que no es funcional.
Por ejemplo aquí.
![image](https://github.com/createchsoftware/armony/assets/159207460/16e5b5fd-fc84-4430-b05d-eaefd435a960)

**Comment by yahirsaavedra** [comment]
Se da prioridad a que ya sea funcional. **NO MARCAR como resuelto hasta que ya sea funcional.**
