### ISSUE TITLE
Horas disponibles

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#79]
No salen las horas disponibles en el calendario.
![image](https://github.com/createchsoftware/armony/assets/159207460/44bd7379-66a9-428a-bc17-4b1c9a77f926)

**Comment by yahirsaavedra** [comment]
De acuerdo a miembros del Departamento, se debe escoger un especialista. Sin embargo, se va a contar como un fallo de frontend, ya que no debería aparecer, entonces, el apartado de "Horas" si no hay, e indicar al usuario que debe escoger primero a un especialista.

Mismo caso, el calendario no deberia ser funcional hasta que se elija especialista, por lo mismo. Queda a debate.

**Comment by ItsJorgeRdz03** [comment]
Existe un orden de selección para que salgan los horarios, en este caso se elige primero el especialista y después el día a agendar, al hacerlo se muestran las horas disponibles con el formato corregido.
