### ISSUE TITLE
Botón siguiente - Paso 4 - Agenda

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#82]
Quitar botón siguiente en el paso 4, en agendar, ya que no se necesita porque están los botones de pago.
![armony31](https://github.com/createchsoftware/armony/assets/159207460/47cfdc33-e2da-4d08-9375-7c6c1de2815e)

**Comment by yahirsaavedra** [comment]
Comentando por Departamento de Análisis, se toma en cuenta.

**Comment by adriandrs** [comment]
Resuelto
