### ISSUE TITLE
QR

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#85]
Poner una etiqueta en "enviar por whatsapp", y seguir el diseño proporciona por diseño, ya que hay botones de mas como el de cancelar y regresar.
![armony32](https://github.com/createchsoftware/armony/assets/159207460/25515f2b-a01d-4015-8c1d-0e0e5138f1ba)

**Comment by yahirsaavedra** [comment]
Comentando por Departamento de Análisis, se toma en cuenta.

**Comment by adriandrs** [comment]
Resuelto
