### ISSUE TITLE
Modificar - Agenda (Mi perfil)

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#87]
Poner etiqueta en modificar, en agenda, en perfil.
![armony33](https://github.com/createchsoftware/armony/assets/159207460/f6bc9d82-259d-44b4-86a2-5dc091a98177)

**Comment by yahirsaavedra** [comment]
Se da prioridad a que ya sea funcional. **NO MARCAR como resuelto hasta que ya sea funcional.**
