### ISSUE TITLE
Cuadro y Botón - Pantalla Suscripción  

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#93]
En la pantalla de suscripcion adaptar el cuadro para que no se salga el texto, Y en el boton de comprar te debe de redirigir al inicio de sesion (modo usuario).
![image](https://github.com/createchsoftware/armony/assets/159207460/554e261c-9d36-4f70-94de-886dfe1f0686)

**Comment by KrisG012** [comment]
Ese problema ya ha sido resuelto, solo que la página a la que se accede con la ip/dominio aún no se ha actualizado.
