### ISSUE TITLE
Cuadro - Pantalla Rangos

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#94]
Acomodar los cuadros en la pantalla de rangos ya que se sale del texto.
![image](https://github.com/createchsoftware/armony/assets/159207460/0911d9f1-f014-4f30-9254-599e10b27dad)

**Comment by KrisG012** [comment]
Al iguan que el issue #93, el problema ya ha sido resuelto, solo que la página a la que se accede con la ip/dominio aún no se ha actualizado.
