### ISSUE TITLE
FUNCIONAL LISTA DE DESEOS

### ISSUE THREAD

**Issue by antonioEsB** [createchsoftware/armony#98]
Hacer funcional la lista de deseos, ósea que en algún producto/servicio le de clic al corazoncito y se me registre lo que seleccione en la lista de deseos.

**Comment by yahirsaavedra** [comment]
Funcional en parte, falta implementar el registro del estatus de cada producto en la lista de deseos del usuario (que el ♥ se quede iluminado o no de acuerdo a la lista)
